# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "hugo-theme-cole"
license = "MIT"
licenselink = "https://github.com/jacobsun/hugo-theme-cole/blob/master/LICENSE"
description = "a hugo theme"
homepage = "https://github.com/jacobsun/hugo-theme-cole"
tags = ["blog"]
features = ["personal", "minimal","light", "simple"]
min_version = 0.5

[author]
  name = "Jacob Sun"
  homepage = "https://ziox.xyz/"
